image: davesilva/docker-experimental

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

build:
  tags:
    - docker
  script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - /builds/davesilva/cross-platform-docker-build/bin/build . davesilva/cross-platform-build-test:$CI_COMMIT_SHA
