version: 2
jobs:
  build-default: &defaults
    working_directory: ~/src
    machine:
      image: circleci/classic:201711-01
    environment:
      PLATFORM: x86_64
    steps:
      - checkout
      - run:
          name: Stop the Docker daemon
          command: sudo service docker stop
      - run:
          name: Set up experimental Docker features
          command: |
            mkdir -p ~/.docker
            echo '{ "experimental": "enabled" }' > ~/.docker/config.json
            sudo echo '{ "experimental": "enabled" }' > /etc/docker/daemon.json
      - run:
          name: Install the latest version of Docker
          command: curl -fsSL https://get.docker.com/ | sudo sh
      - run:
          name: Build the Docker image
          command: docker build --tag cross-platform-test --platform $PLATFORM .

  build-x86_64:
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - build-x86_64
