version: 2
jobs:
  build:
    working_directory: ~/src
    machine:
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Stop the Docker daemon
          command: sudo service docker stop
      - run:
          name: Set up experimental Docker features
          command: |
            mkdir -p ~/.docker
            echo '{ "experimental": "enabled" }' | tee ~/.docker/config.json
            echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
      - run:
          name: Install the latest version of Docker
          command: curl -fsSL https://get.docker.com/ | sudo sh
      - run:
          name: Sign in to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build and push the Docker image
          command: bin/build . davesilva/cross-platform-build-test:$CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - build
